export const INFINITE_SCROLL_STATUS_FAILED = 'INFINITE_SCROLL_STATUS_FAILED';
export const INFINITE_SCROLL_STATUS_MORE_FAILED = 'INFINITE_SCROLL_STATUS_MORE_FAILED';
export const INFINITE_SCROLL_STATUS_MORE_REQUESTED = 'INFINITE_SCROLL_STATUS_MORE_REQUESTED';
export const INFINITE_SCROLL_STATUS_MORE_SUCCEEDED = 'INFINITE_SCROLL_STATUS_MORE_SUCCEEDED';
export const INFINITE_SCROLL_STATUS_REQUESTED = 'INFINITE_SCROLL_STATUS_REQUESTED';
export const INFINITE_SCROLL_STATUS_SUCCEEDED = 'INFINITE_SCROLL_STATUS_SUCCEEDED';
